//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuropeWeather.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EuropeWeatherEntities : DbContext
    {
        public EuropeWeatherEntities()
            : base("name=EuropeWeatherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<WeatherConditions> WeatherConditions { get; set; }
        public virtual DbSet<WeatherData> WeatherData { get; set; }
        public virtual DbSet<WeatherDataConditions> WeatherDataConditions { get; set; }
    }
}
