//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuropeWeather.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeatherData()
        {
            this.WeatherDataConditions = new HashSet<WeatherDataConditions>();
        }
    
        public long WeatherDataId { get; set; }
        public int CityId { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> Pressure { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public Nullable<decimal> MinTemperature { get; set; }
        public Nullable<decimal> MaxTemperature { get; set; }
        public Nullable<int> Visibility { get; set; }
        public Nullable<decimal> WindSpeed { get; set; }
        public Nullable<decimal> WindDirection { get; set; }
        public Nullable<decimal> Clouds { get; set; }
        public Nullable<decimal> Rain { get; set; }
        public Nullable<decimal> Snow { get; set; }
        public Nullable<System.DateTime> Sunrise { get; set; }
        public Nullable<System.DateTime> Sunset { get; set; }
        public Nullable<System.DateTime> TimeOfCalculation { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual Cities Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherDataConditions> WeatherDataConditions { get; set; }
    }
}
