//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuropeWeather.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherConditions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeatherConditions()
        {
            this.WeatherDataConditions = new HashSet<WeatherDataConditions>();
        }
    
        public int WeatherConditionId { get; set; }
        public int ExternalId { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeatherDataConditions> WeatherDataConditions { get; set; }
    }
}
